name: builds

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.11.1.post1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: pip install cython
          CIBW_TEST_REQUIRES: pytest pytest-cov pytest-xdist
          CIBW_TEST_COMMAND: cd {project} && pytest && python tests/benchmark.py

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
